server:
  port: 9083
dubbo:
  application:
    name: product-manage-service
  registry:
    address: zookeeper://192.168.2.131:2181
  protocol:
    port: 20883

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-yl?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "0220"
  data:
    solr:
      host: http://192.168.2.138:8983/solr/ik_core
  rabbitmq:
    host: 192.168.2.142
    username: rabbit
    password: 123456
    port: 5672

